School.create(acara_school_id: 40712, name:	'Palm Avenue School', suburb: 'WESTMEAD', postcode: '2145', state:	'NSW', school_type: 'Special')
School.create(acara_school_id: 40717, name:	'St James College', suburb: 'REDFERN', postcode: '2016', state:	'NSW', school_type: 'Secondary')
School.create(acara_school_id: 40719, name:	'Spinifex State College - Mount Isa - Senior Campus', suburb: 'MOUNT ISA', postcode: '4825', state:	'QLD', school_type: 'Secondary')
School.create(acara_school_id: 40720, name:	'Al Sadiq College Inc', suburb: 'YAGOONA', postcode: '2199', state:	'NSW', school_type: 'Combined')
School.create(acara_school_id: 40722, name:	'New Generation College', suburb: 'MELBOURNE', postcode: '3000', state:	'VIC', school_type: 'Secondary')
School.create(acara_school_id: 40724, name:	'ALESCO Learning Centre', suburb: 'COOKS HILL', postcode: '2300', state:	'NSW', school_type: 'Special')
School.create(acara_school_id: 40726, name:	'Sale College', suburb: 'SALE', postcode: '3850', state:	'VIC', school_type: 'Secondary')
School.create(acara_school_id: 40727, name:	'Geraldton Senior College', suburb: 'GERALDTON', postcode: '6530', state:	'WA', school_type: 'Secondary')
School.create(acara_school_id: 40735, name:	'Royal Far West School', suburb: 'MANLY', postcode: '2095', state:	'NSW', school_type: 'Special')